### ISSUE TITLE
Guide Part: 3.4 (Proving reccot) Does Not Prove with Steps Provided

### ISSUE THREAD

**Issue by Gwen-Fraser** [metamath/lamp-guide#146] opened 2023-10-06 01:55 UTC
The tutorial guide for proving _reccot_ does not prove following the steps as they are. Here is my attempt in which I followed the guide as closely as I could:

```
{"srcs":[{"typ":"Web","fileName":"","url":"https://us.metamath.org/metamath/set.mm","readInstr":"StopBefore","label":"reccot","resetNestingLevel":true,"allLabels":[]}],"descr":"","varsText":"","disjText":"","stmts":[{"label":"8","typ":"p","isGoal":false,"cont":"|- ( A e. CC -> ( sin ` A ) e. CC )","jstfText":": sincl"},{"label":"7","typ":"p","isGoal":false,"cont":"|- ( A e. CC -> ( cos ` A ) e. CC )","jstfText":": coscl"},{"label":"3","typ":"p","isGoal":false,"cont":"|- ( ( ( ( cos ` A ) e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( ( sin ` A ) e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":": recdiv"},{"label":"9","typ":"p","isGoal":false,"cont":"|- ( ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( ( sin ` A ) e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"7 3 : sylanl1"},{"label":"10","typ":"p","isGoal":false,"cont":"|- ( ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( A e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"8 9 : sylanr1"},{"label":"11","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":""},{"label":"2","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 ) -> ( cot ` A ) = ( ( cos ` A ) / ( sin ` A ) ) )","jstfText":": cotval"},{"label":"5","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( cot ` A ) = ( ( cos ` A ) / ( sin ` A ) ) )","jstfText":"2 : 3adant3"},{"label":"6","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( 1 / ( cot ` A ) ) = ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) )","jstfText":"5 : oveq2d"},{"label":"1","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":": tanval"},{"label":"4","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"1 : 3adant2"},{"label":"reccot","typ":"p","isGoal":true,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( 1 / ( cot ` A ) ) )","jstfText":""}]}
```
Here is my attempt to prove the goal of the guide, which was successful with a few more steps:

```
{"srcs":[{"typ":"Web","fileName":"","url":"https://us.metamath.org/metamath/set.mm","readInstr":"StopBefore","label":"reccot","resetNestingLevel":true,"allLabels":[]}],"descr":"","varsText":"","disjText":"","stmts":[{"label":"8","typ":"p","isGoal":false,"cont":"|- ( A e. CC -> ( sin ` A ) e. CC )","jstfText":": sincl"},{"label":"7","typ":"p","isGoal":false,"cont":"|- ( A e. CC -> ( cos ` A ) e. CC )","jstfText":": coscl"},{"label":"3","typ":"p","isGoal":false,"cont":"|- ( ( ( ( cos ` A ) e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( ( sin ` A ) e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":": recdiv"},{"label":"9","typ":"p","isGoal":false,"cont":"|- ( ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( ( sin ` A ) e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"7 3 : sylanl1"},{"label":"10","typ":"p","isGoal":false,"cont":"|- ( ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) /\\ ( A e. CC /\\ ( sin ` A ) =/= 0 ) ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"8 9 : sylanr1"},{"label":"12","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( cos ` A ) =/= 0 /\\ ( sin ` A ) =/= 0 ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"10 : 3impdi"},{"label":"11","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"12 : 3com23"},{"label":"2","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 ) -> ( cot ` A ) = ( ( cos ` A ) / ( sin ` A ) ) )","jstfText":": cotval"},{"label":"5","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( cot ` A ) = ( ( cos ` A ) / ( sin ` A ) ) )","jstfText":"2 : 3adant3"},{"label":"6","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( 1 / ( cot ` A ) ) = ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) )","jstfText":"5 : oveq2d"},{"label":"1","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":": tanval"},{"label":"4","typ":"p","isGoal":false,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( ( sin ` A ) / ( cos ` A ) ) )","jstfText":"1 : 3adant2"},{"label":"reccot","typ":"p","isGoal":true,"cont":"|- ( ( A e. CC /\\ ( sin ` A ) =/= 0 /\\ ( cos ` A ) =/= 0 ) -> ( tan ` A ) = ( 1 / ( cot ` A ) ) )","jstfText":"11 6 4 : 3eqtr4rd"}]}
```
The issue with statements not proving started at 3.4.12, right at the end, and when it says it should be proved it is not. I believe exactly where things went wrong is at this instruction:
```
Select the latest new step with this (long) statement:
|- ( ( ( A e. CC /\ ( cos ` A ) =/= 0 ) /\
     ( A e. CC /\ ( sin ` A ) =/= 0 ) ) ->
     ( 1 / ( ( cos ` A ) / ( sin ` A ) ) ) =
       ( ( sin ` A ) / ( cos ` A ) ) )
```
"Duplicate the step. Click on the second parentheses of the goal statement (so we can duplicate its antecedent) and click on the “copy” icon. Now click on the second parenthesis of our new statement, click on the icon edit (edit) below it, and paste with control-V (or command-V). Enter, then press the icon Unify (unify)."

**Comment by expln** [comment] 2023-10-07 21:57
I have reproduced this exactly as @Gwen-Fraser reported. I noticed that `sin` and `cos` appear in incorrect order when following the guide. According to the guide, I get ```( A e. CC /\ ( sin ` A ) =/= 0 /\ ( cos ` A ) =/= 0 )``` at the end (this is only a fragment from the step in the question). And this does not unify automatically. If I swap `sin` and `cos`, i.e. the statement becomes ```( A e. CC /\ ( cos ` A ) =/= 0 /\ ( sin ` A ) =/= 0 )```, then this step does unify automatically. But the goal step is not proven anyway. At the moment I don't know what happened. I reproduced it on [dev](https://expln.github.io/lamp/dev/index.html). When I have time I will try to reproduce it on older versions to check if the root cause is in mm-lamp changes or not.

**Comment by david-a-wheeler** [comment] 2023-12-27 03:47
Sorry for the problems! I believe PR #149 fixes the problem. I hope @expln will get a chance to review the changes, but if @expln doesn't have time, I'll eventually merge it in regardless, since "instructions don't work" isn't good for anyone :-).

**Comment by david-a-wheeler** [comment] 2023-12-27 03:51
It turns out that instead of a simple unification, you need to apply a bottom-up proof to that step. I suspect I did the bottom-up proof but forgot to write that down, and that ended up being "assume it justifies" (which it does *not*). Due to other changes, the resulting proof looks a little different too (though of course it's still true :-) ). Thanks for the report!

**Comment by david-a-wheeler** [comment] 2023-12-28 16:08
I believe it is now fixed! Let me know of any problems.

**Comment by expln** [comment] 2023-12-28 21:04
Thanks for the fix!

**Closed** 2023-12-29 02:37 UTC
